# 60 straight-line appends building a 960-byte string. With the growable
# handle that is a couple of String allocations and roughly the output size in
# bytes; with a whole-buffer copy per append it is 60 allocations averaging
# half the result -- ~28 KB, and quadratic in the number of chunks. The
# Makefile asserts the bytes stay near the output, which is the property, not
# the representation.
def render
  io = String.new
  io << "<p>chunk 000</p>"
  io << "<p>chunk 001</p>"
  io << "<p>chunk 002</p>"
  io << "<p>chunk 003</p>"
  io << "<p>chunk 004</p>"
  io << "<p>chunk 005</p>"
  io << "<p>chunk 006</p>"
  io << "<p>chunk 007</p>"
  io << "<p>chunk 008</p>"
  io << "<p>chunk 009</p>"
  io << "<p>chunk 010</p>"
  io << "<p>chunk 011</p>"
  io << "<p>chunk 012</p>"
  io << "<p>chunk 013</p>"
  io << "<p>chunk 014</p>"
  io << "<p>chunk 015</p>"
  io << "<p>chunk 016</p>"
  io << "<p>chunk 017</p>"
  io << "<p>chunk 018</p>"
  io << "<p>chunk 019</p>"
  io << "<p>chunk 020</p>"
  io << "<p>chunk 021</p>"
  io << "<p>chunk 022</p>"
  io << "<p>chunk 023</p>"
  io << "<p>chunk 024</p>"
  io << "<p>chunk 025</p>"
  io << "<p>chunk 026</p>"
  io << "<p>chunk 027</p>"
  io << "<p>chunk 028</p>"
  io << "<p>chunk 029</p>"
  io << "<p>chunk 030</p>"
  io << "<p>chunk 031</p>"
  io << "<p>chunk 032</p>"
  io << "<p>chunk 033</p>"
  io << "<p>chunk 034</p>"
  io << "<p>chunk 035</p>"
  io << "<p>chunk 036</p>"
  io << "<p>chunk 037</p>"
  io << "<p>chunk 038</p>"
  io << "<p>chunk 039</p>"
  io << "<p>chunk 040</p>"
  io << "<p>chunk 041</p>"
  io << "<p>chunk 042</p>"
  io << "<p>chunk 043</p>"
  io << "<p>chunk 044</p>"
  io << "<p>chunk 045</p>"
  io << "<p>chunk 046</p>"
  io << "<p>chunk 047</p>"
  io << "<p>chunk 048</p>"
  io << "<p>chunk 049</p>"
  io << "<p>chunk 050</p>"
  io << "<p>chunk 051</p>"
  io << "<p>chunk 052</p>"
  io << "<p>chunk 053</p>"
  io << "<p>chunk 054</p>"
  io << "<p>chunk 055</p>"
  io << "<p>chunk 056</p>"
  io << "<p>chunk 057</p>"
  io << "<p>chunk 058</p>"
  io << "<p>chunk 059</p>"
  io
end

puts render.length
