# Generates lib/regexp/re_casefold.h: the 1:1 simple case foldings, run-length
# encoded. Run it under a CRuby whose Unicode data is the one you want:
#
#   ruby tools/gen_re_casefold.rb > lib/regexp/re_casefold.h
#
# A source whose fold is several codepoints (U+00DF to "ss") is left out: the
# engine compares one codepoint at a time, and CRuby itself is unsettled there.
# Runs are (lo, hi, stride, delta): every cp in lo..hi stepping by stride folds
# to cp + delta.
folds = {}
(0..0x10FFFF).each do |cp|
  next if (0xD800..0xDFFF).cover?(cp)
  ch = begin
    [cp].pack("U")
  rescue RangeError
    next
  end
  f = ch.downcase(:fold)
  next if f == ch
  cps = f.unpack("U*")
  next if cps.size != 1
  folds[cp] = cps[0]
end

runs = []
folds.keys.sort.each do |cp|
  d = folds[cp] - cp
  last = runs.last
  if last && last[:delta] == d
    if last[:hi] == last[:lo] # a run of one takes any stride next
      last[:stride] = cp - last[:lo]
      last[:hi] = cp
      next
    elsif cp - last[:hi] == last[:stride]
      last[:hi] = cp
      next
    end
  end
  runs << { lo: cp, hi: cp, stride: 1, delta: d }
end

puts "/* Generated by tools/gen_re_casefold.rb -- do not edit."
puts "   #{folds.size} simple 1:1 case foldings in #{runs.size} runs."
puts "   Source: CRuby #{RUBY_VERSION}'s Unicode data (String#downcase(:fold)). */"
puts "typedef struct { uint32_t lo, hi; uint16_t stride; int32_t delta; } re_fold_run;"
puts "static const re_fold_run re_fold_runs[] = {"
runs.each { |r| puts "  { 0x%04X, 0x%04X, %d, %d }," % [r[:lo], r[:hi], r[:stride], r[:delta]] }
puts "};"
puts "#define RE_FOLD_RUN_COUNT #{runs.size}"
