# Generates lib/regexp/re_ctype.h: which character types a codepoint above
# ASCII belongs to. Run it under a CRuby whose Unicode data is the one you
# want, the way tools/gen_re_casefold.rb is run:
#
#   ruby tools/gen_re_ctype.rb > lib/regexp/re_ctype.h
#
# The types are the ones CRuby's regexp engine gives the POSIX brackets, and
# they are read off CRuby itself rather than off the Unicode Character
# Database: what this engine has to agree with is CRuby, so asking CRuby is
# both shorter and closer to the question. (Upstream mruby-regexp reads the
# UCD in tools/gen_ctype.rb, because mruby carries the database already.)
#
# `\d`, `\w` and `\s` are ASCII in Ruby's syntax and are not in the table.
# `xdigit` and `ascii` hold nothing above ASCII, so they are not either, and
# `cntrl` holds exactly the C1 controls, which a lookup answers from a pair of
# numbers instead of spending runs on.
#
# The types are held together rather than one range list each: every codepoint
# has one set of answers, so the space above ASCII is cut into the runs over
# which the set does not change, and a run is one 32-bit entry -- the codepoint
# it starts at in the high 21 bits, the set in the low 11. One binary search
# answers every type at once.

TYPES = [
  ["alpha", /[[:alpha:]]/],
  ["upper", /[[:upper:]]/],
  ["lower", /[[:lower:]]/],
  ["digit", /[[:digit:]]/],
  ["alnum", /[[:alnum:]]/],
  ["word",  /[[:word:]]/],
  ["punct", /[[:punct:]]/],
  ["space", /[[:space:]]/],
  ["blank", /[[:blank:]]/],
  ["graph", /[[:graph:]]/],
  ["print", /[[:print:]]/],
]
MASK_BITS = TYPES.size
CNTRL_LO = 0x80
CNTRL_HI = 0x9F
MIN = 0x80
MAX = 0x10FFFF

# A surrogate is no character, and a codepoint that does not encode is none
# either; both take the empty set, which is what the run they fall inside
# already says. Asking CRuby about them is what would raise.
def types_of(cp)
  return 0 if (0xD800..0xDFFF).cover?(cp)
  ch = begin
    [cp].pack("U")
  rescue RangeError
    return 0
  end
  m = 0
  TYPES.each_with_index { |(_, re), i| m |= (1 << i) if ch.match?(re) }
  m
end

runs = []           # [start_cp, mask]
counts = Hash.new(0)
ranges = Hash.new(0)
prev = nil
(MIN..MAX).each do |cp|
  m = types_of(cp)
  runs << [cp, m] if m != prev
  TYPES.each_with_index do |(name, _), i|
    next if (m & (1 << i)).zero?
    counts[name] += 1
    ranges[name] += 1 if prev.nil? || (prev & (1 << i)).zero?
  end
  prev = m
end

out = $stdout
out.puts <<~HEAD
  /* Generated by tools/gen_re_ctype.rb -- do not edit.
     Which character types a codepoint above ASCII belongs to, in #{runs.size} runs.
     Source: CRuby #{RUBY_VERSION}'s Unicode data (the POSIX bracket classes).

     ASCII is not in the table: the compiler sets those bits from a list of
     its own. `\\d`, `\\w` and `\\s` are ASCII in Ruby's syntax and stay so;
     [:xdigit:] and [:ascii:] hold nothing above ASCII. */

  /* The bit each type has in an entry, in the order re_internal.h assigns
     them; re_utf8.c checks that the two agree. */
HEAD
TYPES.each_with_index do |(name, _), i|
  out.puts "#define RE_CTYPE_TABLE_#{name.upcase} 0x%03X" % (1 << i)
end

out.puts format(<<~MID, MASK_BITS - 1, MASK_BITS, MAX, MIN, MASK_BITS, MIN, CNTRL_LO, CNTRL_HI)

  /* One run of codepoints sharing a set of types, as a 32-bit entry:

       bits  0-%d  the set, one bit per type as above
       bits %d-31  the codepoint the run starts at

     Ascending; a run ends where the next begins, and the last at U+%04X.
     The first starts at U+%04X, so a codepoint above ASCII is always inside
     one. */
  #define RE_CTYPE_MASK_BITS %d
  #define RE_CTYPE_MIN 0x%04X

  /* The C1 controls, which is what [[:cntrl:]] holds above ASCII. Not in the
     set: a lookup answers it from these two numbers instead. */
  #define RE_CTYPE_CNTRL_LO 0x%04X
  #define RE_CTYPE_CNTRL_HI 0x%04X

  static const uint32_t re_ctype_runs[] = {
MID

runs.each do |cp, m|
  names = TYPES.each_with_index.select { |(_, _), i| !(m & (1 << i)).zero? }
               .map { |(n, _), _| n }
  out.puts "  0x%08X,  /* U+%04X %s */" % [(cp << MASK_BITS) | m, cp, names.empty? ? "-" : names.join(" ")]
end

out.puts "};"
out.puts
out.puts "#define RE_CTYPE_RUN_COUNT #{runs.size}"
out.puts
out.puts "/* What the table holds, as a check on the data it was built from:"
TYPES.each do |name, _|
  out.puts "     %-7s %7d codepoints in %4d ranges" % [name, counts[name], ranges[name]]
end
out.puts "   and cntrl the #{CNTRL_HI - CNTRL_LO + 1} of U+%04X to U+%04X. */" % [CNTRL_LO, CNTRL_HI]
